# Generated by Django 2.1.5 on 2019-03-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190319_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='links',
        ),
        migrations.AddField(
            model_name='item',
            name='copies',
            field=models.IntegerField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
