# Generated by Django 2.1.5 on 2019-03-19 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20190319_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='status',
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='renter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Waitlist', 'Waitlist'), ('Unavailable', 'Unavailable')], default='Available', max_length=15),
        ),
    ]
