# Generated by Django 2.1.5 on 2019-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20190319_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_owed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(choices=[('Instance', 'Instance'), ('Hold', 'Hold'), ('Reserve', 'Reserve')], default='Instance', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='copies',
            field=models.IntegerField(),
        ),
    ]
